org: polardo662
service: api-alumnos-rds

provider:
  name: aws
  runtime: python3.13
  memorySize: 1024
  timeout: 20
  iam:
    role: arn:aws:iam::552346756840:role/LabRole
  environment:
    SECRET_NAME: rds/alumnos/${sls:stage}
    DB_NAME: ${sls:stage}

functions:
  listar:
    handler: ListarAlumnos.lambda_handler
    package:
      include:
        - ./**  
    events:
      - http:
          path: /alumnos/listar
          method: get
          cors: true
          integration: lambda
